export const actionTypes = {
    // Sample of Action Types List
    HOSTNAME: 'HOSTNAME',
    TRIP_LIST: "TRIP_LIST",
    HEADLINE_DATA: "HEADLINE_DATA",
    TESTIMONIALS_DATA: "TESTIMONIALS_DATA",
    GALLERY_DATA: "GALLERY_DATA",
    GALLERY_TOTAL: "GALLERY_TOTAL",
    MOTOR_DATA: "MOTOR_DATA",
    MY_TRANSACTIONS: "MY_TRANSACTIONS",
    MY_TRANSACTIONS_MORE: "MY_TRANSACTIONS_MORE"
}