export const actionTypes = {
    // Sample of Action Types List
    HOSTNAME: 'HOSTNAME',
    TRIP_LIST: "TRIP_LIST",
    TRIP_DETAIL:"TRIP_DETAIL",
    TRIP_PRICE:"TRIP_PRICE",
    TRIP_MOTOR:"TRIP_MOTOR",
    TRANSACTION_DATA:"TRANSACTION_DATA",
    HEADLINE_DATA: "HEADLINE_DATA",
    TESTIMONIALS_DATA: "TESTIMONIALS_DATA",
    GALLERY_DATA: "GALLERY_DATA",
    GALLERY_TOTAL: "GALLERY_TOTAL",
    MOTOR_DATA: "MOTOR_DATA",
    ACCESSORIES_CATEGORY:"ACCESSORIES_CATEGORY",
    ACCESSORIES_SUBCATEGORY:"ACCESSORIES_SUBCATEGORY",
    ACCESSORIES_DATA:"ACCESSORIES_DATA",
    ACCESSORIES_DETAIL:"ACCESSORIES_DETAIL",
    MY_TRANSACTIONS: "MY_TRANSACTIONS",
    MY_TRANSACTIONS_MORE: "MY_TRANSACTIONS_MORE",
    MY_TRANSACTIONS_FETCHED: "MY_TRANSACTIONS_FETCHED",
    MY_GALLERIES: "MY_GALLERIES",
    MY_GALLERIES_MORE: "MY_GALLERIES_MORE",
    MY_GALLERIES_FETCHED: "MY_GALLERIES_FETCHED"
}