export const actionTypes = {
    // Sample of Action Types List
    HOSTNAME: 'HOSTNAME',
    TRIP_LIST: "TRIP_LIST",
    TRIP_DETAIL:"TRIP_DETAIL",
    TRIP_PRICE:"TRIP_PRICE",
    TRIP_MOTOR:"TRIP_MOTOR",
    TRANSACTION_DATA:"TRANSACTION_DATA",
    HEADLINE_DATA: "HEADLINE_DATA",
    TESTIMONIALS_DATA: "TESTIMONIALS_DATA",
    GALLERY_DATA: "GALLERY_DATA",
    MOTOR_DATA: "MOTOR_DATA",
    ACCESSORIES_CATEGORY:"ACCESSORIES_CATEGORY",
    ACCESSORIES_SUBCATEGORY:"ACCESSORIES_SUBCATEGORY",
    ACCESSORIES_DATA:"ACCESSORIES_DATA",
}