import React from 'react';
import Page from '../components/page';

export default class extends Page {
    static async getInitialProps({ req }) {
        // Inherit standard props from the Page (i.e. with session data)
        let props = await super.getInitialProps({
            req
        });

        if (typeof window === 'undefined') {
            try {
                props.nav = 'blue'
                props.footer = 'transparent'
                props.scrollHeader = false
            } catch (e) { }
        }
        return props;
    }
    constructor(props) {
        super(props);

        this.state = {};
    }
    render() {
        return (
            <div style={{ "minHeight": "77.5vh" }} className="container">
                <div className="mb-4">
                    <a className="pt-4 d-block text-dark h4 title-section" onClick={() => window.history.back()} ><span style={{ top: "-1px" }} className="icon-left-arrow text-sm text-primary position-relative"></span> Back</a>
                </div>
                <div>
                    <div className="mb-3">
                        <h3 className="title-section m-0">TERM AND CONDITION</h3>
                    </div>
                    <div className="mb-3 pb-2">
                        <div className="mt-4">
                            <div>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>SYARAT &amp; KETENTUAN PENGGUNAAN ROAD2RING DI BAWAH INI HARUS DIBACA, DIPAHAMI DAN DIMENGERTI TERLEBIH DAHULU OLEH (PARA) PENGGUNA SEBELUM MENGGUNAKAN SITUS/APLIKASI ROAD2RING. </span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>DENGAN MENGGUNAKAN SITUS/APLIKASI ROAD2RING, MAKA (PARA) PENGGUNA MENERIMA DAN TUNDUK TERHADAP SELURUH SYARAT DAN KETENTUAN PENGUNAAN YANG TERTERA DI BAWAH INI DENGAN SEGALA PERUBAHAN DAN/ATAU TAMBAHANNYA.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>www.road2ring.com (versi web) dan ROAD2RING (versi aplikasi) (keduanya disebut “R2R”), merupakan suatu Situs dan Aplikasi yang dikelola oleh EBIRA. Dengan masuk/mengakses dan/atau menggunakan Situs/Aplikasi ini, dengan berbagai media/alat baik telefon genggam, tablet, komputer, laptop ataupun media lainya, Anda mengakui bahwa Anda telah membaca, memahami, dan menyetujui untuk terikat dan tunduk pada Syarat &amp; Ketentuan yang ditetapkan di bawah ini, termasuk namun tidak terbatas pada segala hal yang tercantum di dalam situs dan aplikasi, yang merupakan bagian yang tidak terpisahkan dari Syarat dan Ketentuan ini. Sehingga dengan menggunakan R2R, Anda dan kami menyatakan kesepakatan perjanjian sesuai dengan apa yang tercantum dalam Syarat dan Ketentuan ini dan segala hal yang terdapat di R2R.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Jika Anda tidak menyetujui Ketentuan Penggunaan, mohon tinggalkan web atau aplikasi R2R. Ketentuan Penggunaan dapat berubah sesuai kebutuhan tanpa pemberitahuan kepada Anda, dan Ketentuan Penggunaan yang berlaku bagi kami dan Anda adalah Ketentuan Penggunaan pada saat Anda menggunakan R2R. </span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>TENTANG ROAD2RING</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>R2R merupakan suatu aplikasi/web yang menyediakan suatu wadah online di mana Anda dapat mencari berbagai pengalaman mengesankan dalam menikmati jalan raya, jalan tanah, jalan berbatu, jalan&nbsp; berpasir dengan mengendarai motor (untuk selanjutnya disebut “Touring”), sambil itu menikmati destinasi wisata di sekitar perjalanan, penginapan dan akomodasi, termasuk namun tidak terbatas pada hotel, kamar dan makan pagi, cottage, ryokan, dan lain-lain (keseluruhan disebut sebagai “Akomodasi”) dan melakukan reservasi dengan Akomodasi tersebut, termasuk membuat pembayaran untuk reservasi Akomodasi tersebut dengan kartu kredit, kartu debit, atau metode pembayaran lainnya untuk memfasilitasi pemrosesan pembayaran tersebut ("Instrumen Pembayaran"). </span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>PROSES PEMESANAN</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Dengan melakukan pemesanan melalui Situs, Anda melakukan penawaran untuk memesan suatu reservasi dengan harga yang telah tertera untuk reservasi tersebut dan ketentuan dan persyaratan lain yang tertera dalam R2R. Hal ini akan menjadi suatu kontrak yang mengikat berdasarkan Ketentuan Penggunaan ketika diterima oleh oleh R2R. Anda akan menerima bukti pesanan Touring dan Akomodasi yang telah dikonfirmasi melalui email konfirmasi, yang berati bahwa pesanan telah dikonfirmasi oleh R2R. Lembar/halaman “Bukti Pesan Touring dan Akomodasi" menandakan bahwa pengajuan pesanan Anda telah diterima dan diproses secara lengkap dan tidak ada lagi yang harus Anda lakukan selain datang pada lokasi dan waktu yang ditentukan oleh kami dalam pelaksanaan Touring.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>TENTANG APLIKASI DAN WEBSITE</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></strong></p>
                                <ol style={{ marginTop: '0cm', marginBottom: '0.0001pt', textAlign: 'left' }}>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Layanan yang tersedia dalam Website ini secara umum menggunakan system re-marketing dan sistem cookies yang memungkinkan pihak ketiga (termasuk dan tidak terbatas pada Google) mengakses dan menggunakan data kunjungan dalam sistem Cookies website ini untuk menampilkan dan menayangkan kembali tiap iklan R2R melalui internet.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Anda tidak boleh membuat link, melakukan screen capture atau data crawling ke Website tanpa adanya persetujuan tertulis sebelumnya dari R2R. Hal-hal tersebut dianggap sebagai pelanggaran hak milik intelektual R2R.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Website ini dan produk-produk, teknologi dan proses yang terdapat atau terkandung dalam Website dan aplikasi dimiliki oleh R2R atau pihak ketiga yang memberi hak kepada Kami. Kecuali untuk penggunaan yang secara tegas diijinkan dan diperbolehkan dalam Syarat dan Ketentuan Penggunaan R2R ini, Anda tidak memiliki ataupun menerima dan R2R tidak memberikan hak lain apapun kepada Anda atas Website atau aplikasi R2R, berikut dengan segala data, informasi dan konten didalamnya.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Dalam Website ini mungkin terdapat link (tautan) ke website yang dikelola oleh pihak ketiga ("Situs Eksternal"). Situs Eksternal disediakan hanya untuk referensi dan kenyamanan saja. R2R tidak mengoperasikan, mengendalikan atau mendukung dalam bentuk apa pun Situs Eksternal yang bersangkutan ataupun konten/isinya. Anda bertanggung jawab penuh atas penggunaan Situs Eksternal tersebut dan dianjurkan untuk mempelajari syarat dan ketentuan dari Situs Eksternal itu secara seksama.</span></li>
                                </ol>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>TENTANG PENGGUNA</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></strong></p>
                                <ol style={{ marginTop: '0cm', marginBottom: '0.0001pt', textAlign: 'left' }}>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Untuk dapat menggunakan R2R baik dalam versi web ataupun versi aplikasi, Anda harus telah berusia 18 (delapan belas) tahun pada tanggal Anda menggunakan R2R. </span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Pengguna R2R harus memiliki SIM (Surat Izin Mengemudi) motor yang berlaku pada saat melakukan touring bersama R2R.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Passport &amp; STNK (Surat Tanda Nomor Kendaraan Bermotor) motor yg disewa harus di kumpulkan kepada Road Captain (disingkat RC) selama perjalanan dan selama menikmati layanan R2R.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Pada saat reservasi, Anda diwajibkan membuat Perjanjian Sewa Motor dan/atau Perjanjian Sewa Peralatan Motor yang dibuat dan disepakati bersama secara elektronik.</span></li>
                                </ol>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>BATASAN PENGGUNAAN</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>R2R memberikan batasan bahwa penggunaan situs ini tidak eksklusif, tidak dapat dipindahtangankan, tidak dapat dilisensikan sesuai dengan syarat dan ketentuan yang terkandung di situs. Anda setuju bahwa Anda :</span></p>
                                <ol style={{ marginTop: '0cm', marginBottom: '0.0001pt', textAlign: 'left' }}>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Mengunakan situs ini hanya untuk melakukan pemesanan atau pembelian dan tidak boleh menggunakan situs ini untuk hal-hal lain, termasuk namun tidak terbatas pada membuat reservasi atau pemesanan palsu.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Tidak akan menggunakan alamat email palsu atau data pribadi palsu yang dikirimkan ke situs ini. Anda setuju bahwa akan bertanggung jawab atas segala kerusakan dan/atau pelanggaran yang disebabkan oleh pelanggaran hak cipta atau hak kepemilikan lainnya atau setiap kerugian atau kerusakan yang diakibatkan dari penggunaan situs ini.</span></li>
                                </ol>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>PEMBAYARAN DENGAN KARTU KREDIT/DEBIT</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Untuk pesanan Akomodasi yang dibayarkan di muka kepada R2R, Anda mengizinkan kami mengumpulkan dan memproses (termasuk mengumpulkan dan memproses melalui pihak ketiga) informasi Anda sebagaimana diwajibkan oleh penyedia jasa atau institusi keuangan yang menerbitkan Instrumen Pembayaran Anda seperti kartu kredit atau debit untuk memverifikasi identitas Anda. Informasi pribadi mengenai Anda yang dikumpulkan dan mungkin dibagikan ke pihak ketiga (termasuk untuk menangani transaksi Anda dan/atau mengelola akun Anda) diatur dalam Kebijakan Privasi.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Apabila terjadi penyalahgunaan Instrumen Pembayaran atau penggunaan yang tidak berwenang atas Instrumen Pembayaran Anda oleh pihak ketiga, Anda wajib menghubungi bank atau penerbit kartu Anda secepatnya setelah mengetahui adanya penggunaan tanpa izin tersebut. Jika Anda mencurigai telah terjadi pemesanan yang tidak berwenang atau yang bersifat penipuan melalui R2R, mohon segera hubungi tim Layanan Pelanggan kami.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Anda menegaskan bahwa kartu kredit atau kartu debit yang Anda gunakan adalah milik Anda sendiri, atau Anda berwenang menyelesaikan pemesanan menggunakan kartu ini, serta memiliki dana yang cukup untuk menutup biaya transaksi tersebut. Anda menerima tanggung jawab finansial atas semua transaksi yang dilakukan atas nama atau atas rekening Anda.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Anda menyatakan bahwa informasi yang Anda berikan kepada kami dalam melakukan pemesanan adalah benar sepenuhnya. R2R berhak untuk tidak menerima Instrumen Pembayaran tertentu. R2R dapat menambahkan atau menghapus metode pembayaran lain atas kebijakannya sendiri. Untuk kenyamanan Anda, saat ini R2R juga menawarkan pilihan untuk menyimpan informasi Instrumen Pembayaran Anda dengan aman. Untuk informasi lebih lanjut, silakan lihat Kebijakan Privasi kami.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>KEBIJAKAN PRIVASI</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Untuk keperluan kebijakan privasi ini, informasi pribadi adalah segala informasi yang dapat ditautkan ke individu tertentu, termasuk namun tidak terbatas pada informasi, seperti nama, alamat, nomor telepon, alamat email dan nomor kartu kredit dan perlu diketahui untuk menggunakan layanan kami. berarti situs web:</span></p>

                                <ol style={{ marginTop: '0cm', marginBottom: '.0001pt' }}>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Anda setuju, jika Anda memberi tahu informasi pribadi kepada kami, maka kami akan membuat salinan data (catatan basis data) tentang Anda.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Jika Anda mendaftar di situs web kami, mengunduh materi atau melakukan transaksi lainnya. Anda setuju untuk kami mengumpulkan informasi pribadi yang diperlukan untuk menyediakan layanan yang Anda inginkan. Dan Anda setuju untuk memperbarui informasi Anda oleh operator untuk diberitahukan kepada mitra layanan (yang mungkin merupakan pihak ketiga).</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Anda setuju bahwa Operator dapat menghubungi Anda untuk memberikan informasi tentang produk dan layanan yang mungkin menarik bagi Anda (kecuali Anda telah menyatakan bahwa Anda tidak menginginkan informasi apa pun dari Operator).</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Jika Anda terus-menerus menggunakan situs web kami, maka tunjukkan bahwa Anda setuju dengan perubahan yang akan muncul dalam kebijakan privasi ini.</span></li>
                                </ol>

                                <div id="refund" className="invisible">
                                    <h3>targetrefund</h3>
                                </div>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>PEMESANAN DAN PEMBATALAN UNTUK PEMBELIAN</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Harap dicatat bahwa syarat dan ketentuan untuk pembatalan pemesanan dan pembelian akan bervariasi untuk setiap produk dan layanan. Mengacu pada syarat dan ketentuan untuk produk atau layanan tertentu, dapat diperiksa melalui kantor Penjualan dan Layanan Pelanggan kami selama jam operasional kantor. Pembatalan, atas permintaan Anda, mungkin tidak diizinkan atau mungkin memerlukan waktu pemrosesan minimum periode yang berbeda, sesuai dengan syarat dan ketentuan yang spesifik untuk jenis produk atau layanan yang dibeli. </span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>R2R tidak akan melakukan refund terhadap dana yang sudah ditransfer kepada Pengguna, kecuali :</span></p>
                                <ol style={{ marginTop: '0cm', marginBottom: '0.0001pt', textAlign: 'left' }}>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Kendaraan yang sudah di sewa oleh Anda tidak bisa digunakan.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>Trip yang telah Anda pesan kemudian dibatalkan secara sepihak oleh R2R.</span></li>
                                    <li style={{ margin: '0cm 0cm 0.0001pt 0px', lineHeight: 'normal', fontSize: '11pt' }}><span style={{ fontSize: '12.0pt' }}>RC tidak hadir/datang pada saat tanggal keberangkatan.</span></li>
                                </ol>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Refund dengan alasan selain 3 (tiga) hal diatas, hanya dapat dilakukan jika Anda membayar asuransi pembatalan dengan besaran premi sesuai dengan yang tertera dalam formulir pemesanan asuransi.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Bencana alam yang terjadi H-30 sebelum tanggal keberangkatan, hanya akan ditukar tanggal lain/jadwal touring lain yang akan diberitahukan oleh R2R.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Pembayaran tidak dapat di refund, hanya bisa di reschedule jadwal untuk touring berikutnya paling lambat H-45 dengan harga menyesuikan trip yang baru. </span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>HAK ATAS KEKAYAAN INTELEKTUAL</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Merek/logo "ROAD2RING” adalah merek dagang terdaftar dari atau memiliki lisensi dari ROAD2RING dan/atau anak perusahaannya. Nama produk dan perusahaan yang disebutkan dalam Situs dapat berupa nama, merek dagang, nama dagang, merek jasa, logo, simbol atau nama hak milik lainnya dari ROAD2RING, pemberi lisensinya, atau perusahaan terasosiasi atau pihak ketiga. Penggunaan dalam Situs atas setiap nama, nama dagang, merek dagang, merek jasa, logo, simbol atau nama hak milik, atau penandaan dari atau kepemilikan pihak ketiga, dan persediaan dari barang atau jasa tertentu dari pihak ketiga tersebut melalui Situs, tidak dapat diartikan sebagai suatu dukungan atau sponsor dari Situs oleh pihak ketiga tersebut, atau keikutsertaan dari pihak ketiga tersebut dalam penawaran barang, jasa atau informasi melalui Situs. ROAD2RING memiliki hak cipta terhadap Situs. Anda tidak dapat menggunakan hak atas kekayaan intelektual dari ROAD2RING tanpa persetujuan kami.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Situs memuat materi hak cipta, nama dagang dan informasi hak milik lainnya, termasuk, namun tidak terbatas pada, kata-kata, perangkat lunak, foto, grafis dan mungkin di kemudian hari mencakup video, grafis, musik dan suara. Seluruh isi dari Situs dilindungi oleh undang-undang hak cipta. Kami, dan para pemberi lisensi kami, memiliki hak cipta dan/atau hak database dalam pemilihan, koordinasi, pengaturan dan perbaikan dari isi tersebut, juga dalam isi aslinya. Anda tidak dapat mengubah, menerbitkan, mengirim, ikut serta dalam mengalihkan atau menjual, menciptakan pekerjaan derivatif, atau dengan cara apa pun mengeksploitasi, setiap isi, secara keseluruhan atau sebagian, kecuali sebagaimana telah diatur dalam Ketentuan Penggunaan.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><strong><span style={{ fontSize: '12.0pt' }}>NASEHAT PERJALANAN</span></strong></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Walaupun banyak perjalanan yang dapat diselesaikan tanpa adanya insiden apa pun, perjalanan ke tujuan-tujuan tertentu mungkin melibatkan resiko yang lebih besar daripada tujuan lainnya. Kami menganjurkan para penumpang untuk membaca larangan perjalanan, peringatan, pengumuman dan nasehat yang diterbitkan oleh pemerintah mereka sebelum melakukan pemesanan perjalanan, khususnya pada saat melakukan perjalanan ke tujuan internasional.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Dengan menampilkan Akomodasi di tujuan tertentu apa pun, R2R tidak menyatakan atau menjamin bahwa perjalanan ke tujuan tersebut adalah dianjurkan atau bebas dari resiko, dan R2R tidak pernah dapat dinyatakan bertanggung jawab untuk kerusakan atau kerugian yang mungkin disebabkan oleh perjalanan ke tujuan tersebut. R2R dalam keadaan apa pun, tidak dapat dinyatakan bertanggung jawab untuk insiden apa pun yang terjadi selama Anda menginap di Akomodasi. Anda sangat dianjurkan untuk membaca nasehat perjalanan yang bersangkutan, yang diterbitkan oleh pemerintah Anda untuk setiap negara yang akan Anda kunjungi, dan untuk melakukan segala upaya pencegahan yang diperlukan. Anda juga dianjurkan untuk mengambil asuransi perjalanan pribadi.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>R2R tidak dapat dinyatakan bertanggung jawab untuk setiap kerugian yang ditimbulkan dalam hal terjadi kelalaian di pihak Anda untuk memiliki paspor, visa dan dokumentasi yang diperlukan untuk perjalanan Anda. Anda dianjurkan untuk menanyakannya kepada kedutaan, konsulat dan/atau departemen visa dari negara yang hendak Anda kunjungi. Anda bertanggungjawab untuk memperoleh dokumen perjalanan apa pun yang diperlukan.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Mohon perhatikan bahwa beberapa negara memiliki hukum dan peraturan yang ketat mengenai impor barang, unit atau substansi yang dibatasi atau dilarang. Hal ini dapat mencakup namun tidak terbatas pada alkohol, tembakau, parfum, narkoba, obat-obatan, buku, film, DVD, materi hiburan dewasa, makanan, tumbuhan, bagian dari hewan, dan lain-lain. Anda bertanggungjawab untuk memeriksa dan mematuhi peraturan yang berlaku. Ketidakpatuhan akan berakibat pada hukuman yang berat.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Suatu peristiwa keadaan kahar adalah suatu peristiwa di luar pengendalian Pihak Yang Dilindungi, dan dapat mencakup, namun tidak terbatas pada, bencana alam, kondisi cuaca, kebakaran, insiden nuklir, getaran elektro-magnetik, tindakan teroris, kerusuhan, perang, serangan yang menyebabkan kebakaran, huru-hara, pemberontakan, kekerasan bersenjata dalam bentuk apa pun, sengketa perburuhan, lock-out, pemogokan, kekurangan, tindakan atau larangan pemerintah, pencurian, kepailitan, rusaknya mesin, terputusnya atau gangguan jaringan atau sistem, terputusnya internet dan komunikasi, karantina, epidemi, pandemi, dan lain-lain. Tidak ada tanggung jawab yang akan diterima untuk setiap pengeluaran, kelalaian, keterlambatan, perubahan arah atau tindakan dari pihak pemerintah yang berwenang. Tidak ada Pihak Yang Dilindungi yang akan bertanggung jawab atas setiap pelanggaran oleh Akomodasi terhadap setiap persyaratan atau jaminan, termasuk, namun tidak terbatas pada, persyaratan atau jaminan yang tersirat akan suatu kesesuaian untuk tujuan tertentu atau dapat diperdagangkan, Pihak Yang Dilindungi tidak akan bertanggung jawab atas setiap kesalahan dari Akomodasi (termasuk setiap kewajiban dalam suatu perbuatan melawan hukum), sehubungan dengan setiap produk dan/atau jasa yang disediakan di Situs. R2R tidak menjamin akses yang berkelanjutan tanpa adanya gangguan kepada Situs.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>R2R hanya akan bertanggung jawab sesuai dengan hukum yang berlaku apabila bersalah karena terlibat dalam kesalahan yang disengaja atau kelalaian dalam memberikan layanan yang sesuai. Sejauh diizinkan oleh hukum yang berlaku dan tanpa mengurangi pembatasan yang diatur dalam Ketentuan Penggunaan, kewajiban keseluruhan R2R tidak akan melebihi jumlah yang lebih rendah dari (a) jumlah keseluruhan biaya reservasi Anda sebagaimana tertera dalam email konfirmasi (baik untuk satu peristiwa atau sekelompok peristiwa yang terkait) atau (b) Dua ratus lima puluh dolar Amerika (atau jumlah yang setara dalam mata uang lokal). Apabila ada kesalahan atau kelebihan penagihan yang dilakukan oleh R2R, Anda dapat mengajukan tuntutan terkait kelebihan pembebanan tersebut terlepas dari apa yang disebutkan di atas.</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>&nbsp;</span></p>
                                <p style={{ margin: '0cm 0cm 0.0001pt', lineHeight: 'normal', fontSize: '11pt', textAlign: 'left' }}><span style={{ fontSize: '12.0pt' }}>Sebagai tambahan, pembatasan atau pengecualian dari kewajiban yang disebutkan di atas tidak dapat diterima berdasarkan peraturan hukum yang berlaku. Dalam hal tersebut, R2R bertanggung jawab sejauh diizinkan oleh peraturan hukum yang terkait. Tuntutan harus dikirimkan sesegera mungkin setelah peristiwa terjadi. Pengiriman tuntutan yang tertunda akan dianggap tidak berlaku berdasarkan peraturan pembatasan yang berlaku. Hanya tuntutan yang memenuhi syarat yang dianggap.</span></p>
                            </div>
                        </div>
                    </div>

                </div>
                <div className="py-3" />
            </div>
        );
    }
}
